# PromptMan/.github/workflows/main.yml
name: PromptMan Backend CI/CD to Google Cloud Run

on:
  push:
    branches:
      - main 
    # triggers
    paths:
      - 'backend/**'
      - '.github/workflows/main.yml'
  
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-south1
  ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
  
  # Names
  BACKEND_IMAGE_NAME: promptman-backend
  BACKEND_SERVICE_NAME: promptman-backend

  # Use unique Docker image SHA tag for traceability
  IMAGE_TAG: ${{ github.sha }}
  
  BUILD_REGION: asia-east1

jobs:
  # builder
  build_backend_image:
    name: Build & Push Backend Image
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    outputs:
      image_uri: ${{ steps.submit_backend_build.outputs.image_uri }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Submit Backend Build using Cloud Build
        id: submit_backend_build
        run: |
          TARGET_IMAGE_URI="${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo "Submitting Backend Build for Image: $TARGET_IMAGE_URI"
          
          gcloud builds submit ./backend \
            --tag "$TARGET_IMAGE_URI" \
            --project=${{ env.GCP_PROJECT_ID }} \
            --region=${{ env.BUILD_REGION }} \
            --quiet
            
          echo "image_uri=$TARGET_IMAGE_URI" >> $GITHUB_OUTPUT

  # deployer
  deploy_backend:
    name: Deploy Backend Service
    runs-on: ubuntu-latest
    needs: build_backend_image 
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Deploy Backend to Cloud Run
        run: |
          IMAGE_URI="${{ needs.build_backend_image.outputs.image_uri }}"
          echo "Deploying Backend Image: $IMAGE_URI"
          
          ENV_VARS="PYTHONUNBUFFERED=1"
          ENV_VARS+=",REDIS_HOST=${{ secrets.PROD_REDIS_HOST_IP }}"
          ENV_VARS+=",REDIS_PORT=${{ secrets.PROD_REDIS_INSTANCE_PORT }}"
          ENV_VARS+=",ALLOWED_ORIGINS=${{ secrets.PROD_BACKEND_ALLOWED_ORIGINS }}"
          ENV_VARS+=",ANALYTICS_DATABASE_URL=${{ secrets.ANALYTICS_DATABASE_URL }}"

          gcloud run deploy ${{ env.BACKEND_SERVICE_NAME }} \
            --image "$IMAGE_URI" \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --port 8000 \
            --allow-unauthenticated \
            --set-env-vars="$ENV_VARS" \
            --memory=4Gi \
            --cpu=2 \
            --project=${{ env.GCP_PROJECT_ID }} \
            --quiet